#define NODE_DOUBLE 'D'
#define NODE_STRING 'S'
#define NODE_ASGN 'A'
#define NODE_REFERENCE 'R'
#define NODE_IF 'I'
#define NODE_WHILE 'W'
#define NODE_GET 'G'
#define NODE_PAZIENTE 'P'
#define NODE_REGISTRO 'O'
#define NODE_ADD_PAZIENTE 'E'
#define NODE_EQUAL '='
#define NODE_SEQOP 'L'
#define NODE_GETPAZ 'T'
#define NODE_NUMPAZ 'Z'
#define NODE_NUMPOS 'B'
#define NODE_NUMRIC 'C'
#define NODE_PAZIENTE_FILTER 'F'

#define REGEX_DATA "^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)[[:digit:]][[:digit:]]$"
#define REGEX_COUNTRY "[a-zA-Z]+"
